spring.application.name=bfhl
server.port=${PORT:8080}

# User configuration - UPDATE THESE WITH YOUR ACTUAL DETAILS
bfhl.user.id=abhilasha_kumari_21012005
bfhl.user.email=abhilashakumari231221@acropolis.in
bfhl.user.roll-number=0827IT231005
